services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=<INSERT your VPN provider>
      - OPENVPN_USER=<INSERT user>
      - OPENVPN_PASSWORD=<INSERT user auth>
      - SERVER_COUNTRIES=Switzerland # You can change this but I advice Switzerland
      - TZ=Europe/Brussels
      - LOG_LEVEL=info
    volumes:
      - /home/ken/docker/gluetun:/gluetun
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    environment:
      - PUID=<INSERT puid>
      - PGID=<INSERT pgid>
      - TZ=Europe/Brussels
      - WEBUI_PORT=8080
    volumes:
      - /home/ken/docker/qbittorrent/config:/config
      - /mnt/media/Downloads:/downloads
      - /srv/temp_downloads/incomplete:/incomplete
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=<INSERT puid>
      - PGID=<INSERT pgid>
      - TZ=Europe/Brussels
    volumes:
      - <INSERT config location>:/config
      - <INSERT media location>:/media
      - <INSERT media download location>:/downloads
    networks:
      - arrnet
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=<INSERT puid>
      - PGID=<INSERT pgid>
      - TZ=Europe/Brussels
    volumes:
      - <INSERT config location>:/config
    networks:
      - arrnet
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - arrnet
    ports:
      - 8191:8191
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=<INSERT puid>
      - PGID=<INSERT pgid>
      - TZ=Europe/Brussels
    volumes:
      - <INSERT config location>:/config
      - <INSERT media location>:/media
      - <INSERT media download location>:/downloads
    networks:
      - arrnet
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=<INSERT puid>
      - PGID=<INSERT pgid>
      - TZ=Europe/Brussels
    volumes:
      - <INSERT config location>:/config
      - <INSERT media location>:/media
      - <INSERT media download location>:/downloads
    networks:
      - arrnet
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  arrnet:
    driver: bridge
